const router = require("express").Router();
const pool = require("../db");
const bcrypt = require("bcrypt");
const verifyToken = require("../middleware/verifyToken");

/* =========================
   GET ALL RESIDENTS
========================= */
router.get("/", async (req, res) => {
  try {
    const result = await pool.query(
      `
      SELECT 
        *,
        to_char("Birthday", 'YYYY-MM-DD') AS "Birthday"
      FROM resident
      ORDER BY "ResidentID" DESC
      `
    );

    return res.json({ residents: result.rows });
  } catch (err) {
    console.error("GET /residents Error:", err.message);
    return res.status(500).json({ error: err.message });
  }
});

/* =========================
   GET RESIDENT STATUS
   IMPORTANT: must come BEFORE /:id
========================= */
router.get("/:id", async (req, res) => {
  console.log("HIT /residents/:id =", req.params.id);
  try {
    const { id } = req.params;

    const result = await pool.query(
      `
      SELECT
        "ResidentID",
        "FirstName",
        "MiddleName",
        "LastName",
        "Age",
        to_char("Birthday", 'YYYY-MM-DD') AS "Birthday",
        "Gender",
        "CivilStatus",
        "ResidentType",
        "VoterStatus",
        "HouseNumber",
        "StreetAddress",
        "ContactNumber",
        "Email",
        "FatherName",
        "MotherName",
        "SpouseName",
        "NoOfChildren",
        "ContactPerson",
        "ContactPersonNo",
        "ContactPersonAddress",
        "BarangayCard",
        "ResidentAccountID",
        "status"
      FROM resident
      WHERE TRIM("ResidentID") = TRIM($1)
      LIMIT 1
      `,
      [id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: "Resident not found" });
    }

    // ✅ Matches frontend usage: data.FirstName, data.MiddleName, data.LastName, etc.
    return res.json(result.rows[0]);
  } catch (err) {
    console.error("GET /residents/:id Error:", err.message);
    return res.status(500).json({ error: err.message });
  }
});

/* =========================
   REGISTER RESIDENT (Admin/SuperAdmin)
   POST /residents/register
   Requires Authorization: Bearer <token>
========================= */
router.post("/register", verifyToken, async (req, res) => {
  const client = await pool.connect();

  const toBool = (v) => {
    if (v === true || v === false) return v;
    if (typeof v === "string") {
      const s = v.trim().toLowerCase();
      if (s === "true" || s === "yes" || s === "1") return true;
      if (s === "false" || s === "no" || s === "0") return false;
    }
    if (typeof v === "number") return v === 1;
    return false;
  };

  try {
    // ✅ Only admins should create residents
    const isAdminActor = req.user?.type === "superadmin" || req.user?.type === "barangayadmin";
    const actorId = req.user?.superAdminId || req.user?.barangayAdminId || null;

    if (!isAdminActor || !actorId) {
      return res.status(403).json({ error: "Only admin/superadmin can register residents." });
    }

    const {
      firstName,
      middleName,
      lastName,
      age,
      birthday,
      gender,
      civilStatus,
      residentType,
      voterStatus,
      houseNo,
      streetAddress,
      contactNumber,
      email,
      fatherName,
      motherName,
      spouseName,
      numberOfChildren,
      emergencyContactName,
      emergencyContactNumber,
      emergencyContactAddress,
      password,
    } = req.body;

    if (!password) {
      return res.status(400).json({ error: "Password is required" });
    }
    if (!firstName || !lastName || !age || !birthday || !gender || !civilStatus || !residentType || !contactNumber || !email) {
      return res.status(400).json({ error: "Missing required resident fields." });
    }

    await client.query("BEGIN");

    // 1) Insert resident (ResidentID generated by trigger)
    const residentInsert = await client.query(
      `
      INSERT INTO resident (
        "FirstName", "MiddleName", "LastName", "Age", "Birthday",
        "Gender", "CivilStatus", "ResidentType", "VoterStatus", "HouseNumber",
        "StreetAddress", "ContactNumber", "Email", "FatherName", "MotherName",
        "SpouseName", "NoOfChildren", "ContactPerson", "ContactPersonNo",
        "ContactPersonAddress", "BarangayCard", "status"
      )
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,'Active')
      RETURNING *
      `,
      [
        firstName,
        middleName || null,
        lastName,
        parseInt(age, 10),
        birthday,
        gender,
        civilStatus,
        residentType,
        toBool(voterStatus),
        houseNo || null,
        streetAddress || null,
        contactNumber,
        email,
        fatherName || null,
        motherName || null,
        spouseName || null,
        parseInt(numberOfChildren, 10) || 0,
        emergencyContactName || null,
        emergencyContactNumber || null,
        emergencyContactAddress || null,
        "N/A",
      ]
    );

    const newResidentId = residentInsert.rows[0]?.ResidentID || residentInsert.rows[0]?.residentid;

    if (!newResidentId) {
      throw new Error("Failed to get newly generated ResidentID.");
    }

    // 2) Insert residentaccount
    const saltRounds = 12;
    const passwordHash = await bcrypt.hash(password, saltRounds);

    await client.query(
      `INSERT INTO residentaccount ("ResidentID", "Password", "Role")
       VALUES ($1, $2, $3)`,
      [newResidentId, passwordHash, "Resident"]
    );

    // 3) ✅ Log transaction BEFORE COMMIT (same DB transaction)
    await client.query(
      `
      INSERT INTO transaction_history
        ("RequestID","ResidentID","Action","RequestStatus","RequestType","RequestPurpose","CreatedAt")
      VALUES
        ($1,$2,$3,$4,$5,$6,NOW())
      `,
      [
        null,
        actorId,
        "Created Resident Account",
        "Success",
        "Resident Records",
        `Created resident: ${newResidentId}`,
      ]
    );

    await client.query("COMMIT");
    return res.status(201).json(residentInsert.rows[0]);
  } catch (err) {
    try {
      await client.query("ROLLBACK");
    } catch { }
    console.error("REGISTER ERROR:", err);
    return res.status(500).json({ error: err.message || "Database failed to save record." });
  } finally {
    client.release();
  }
});

/* =========================
   UPDATE RESIDENT STATUS
========================= */
router.patch("/:id/status", async (req, res) => {
  try {
    const { id } = req.params;
    const { status } = req.body;

    if (!status || !["Active", "Inactive"].includes(status)) {
      return res.status(400).json({ error: "Status must be Active or Inactive" });
    }

    const result = await pool.query(
      `
      UPDATE resident
      SET "status" = $1
      WHERE "ResidentID" = $2
      RETURNING *
      `,
      [status, id]
    );

    if (result.rowCount === 0) {
      return res.status(404).json({ error: "Resident not found", idSent: id });
    }

    return res.json({ message: "Status updated", updated: result.rows[0] });
  } catch (err) {
    console.error("PATCH /residents/:id/status error:", err.message);
    return res.status(500).json({ error: err.message });
  }
});

module.exports = router;